name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Instalar Pylint
        run: pip install pylint

      - name: Rodar Pylint e gerar relatório JSON
        run: pylint --output-format=json **/*.py > pylint-report.json

      - name: Listar arquivos no diretório
        run: ls -alh

      - name: Upload Pylint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: pylint-report.json
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false


