name: Continuous Delivery  # Corrigido nome do workflow

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        run: echo "Simulando deploy..."

      - name: Upload Projeto Zipado
                - uses: actions/upload-artifact@v4
                with:
                  name: projetozipado.zip
                  path:
                    - '**/*.py'
                    - README.md
                    - 