name: Continuos Integration
on:
  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
          linter: pylint
                    - name: Upload Lint Report
                    uses: actions/upload-artifact@v4
                    with:
                      name: lint-results
                      path: pylint-report.json
                      





