name: Run Unit Tests

on:
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: pylint-report.json








