name: Discord Commit Notification

on:
  push:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enviar notificação para o Discord
        uses: tsickert/discord-webhook@v5
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
              Novo commit enviado!
              Autor: ${{ github.actor }}
              Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
