name: Discord Commit Notification

on:
  push:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para o Discord
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SLACK_MESSAGE: " Novo commit feito por ${{ github.actor }}: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
