name: Discord Commit Notification

on:
  push:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Discord Webhook
        uses: Ilshidur/action-discord@v2  # Alternativa estável
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🚀 Novo commit foi feito no repositório!"

