name: Discord Commit Notification

on:
  push:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enviar mensagem para o Discord
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          args: " Um novo commit foi enviado para o repositório!"
